<a href="https://colab.research.google.com/github/dnsgud/git_test2/blob/master/numpy(np)%EC%9D%98%EC%83%9D%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [ ]:
np.array(1)

In [7]:
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [9]:
l = [
     [1,2],
     [3,4]
]
np.array(l)

array([[1, 2],
       [3, 4]])

In [13]:
#연속된 리스트
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
a = np.arange(0,10,0.1,dtype=np.float64)
a.shape

(100,)

In [23]:
a.ndim

1

In [26]:
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [45]:
a = np.zeros((3,5),dtype=int)

In [46]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [48]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
#등간수열
np.linspace(0,20,num=21)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [58]:
#대각선
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
np.random.rand(3,5)

array([[0.66156507, 0.78965541, 0.09478866, 0.66959155, 0.71985411],
       [0.02196356, 0.41563551, 0.5876577 , 0.73647863, 0.72091586],
       [0.81424743, 0.55438118, 0.59832826, 0.14249499, 0.20348843]])

In [65]:
np.random.randn(3,5)

array([[-1.2391071 , -1.62230633, -0.17277086,  0.43663969,  0.62632684],
       [-0.30975251, -0.65238724,  1.23901338,  0.70605357, -0.90659434],
       [ 1.40514707,  1.54110056,  0.11285677, -0.205882  ,  1.00132871]])

In [93]:
#0부터5중 랜덤
np.random.randint(0,5,size=(5,5))

array([[2, 0, 4, 2, 0],
       [3, 0, 3, 1, 1],
       [4, 1, 4, 2, 0],
       [0, 3, 2, 1, 2],
       [2, 4, 2, 4, 0]])

In [100]:
np.random.randint([2,5,6,8,9],[[10],[20]])

array([[ 4,  6,  7,  9,  9],
       [ 6,  9, 14, 15, 19]])

In [116]:
#랜덤값 지정
np.random.seed(10)
np.random.randn(10)

array([ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597,
       -0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021])

In [ ]:
np.arange(5*5).reshape(5,5)

In [117]:
np.arange(3*5*5).reshape(3,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [124]:
np.random.seed(100)
rand = np.random.randint(0,100,25)
print(rand)
np.max(rand)
np.min(rand)

[ 8 24 67 87 79 48 10 94 52 98 53 66 98 14 34 24 15 60 58 16  9 93 86  2
 27]


2

In [126]:
np.random.seed(100)
rand = np.random.randint(0,100,25)
print(rand)
idx = np.argmin(rand)
print(rand[idx])

[ 8 24 67 87 79 48 10 94 52 98 53 66 98 14 34 24 15 60 58 16  9 93 86  2
 27]
2


In [137]:
a = np.arange(1.,6)
b = np.array([1.,2,3,4,5])
np.all(a)


True

In [139]:
a = np.arange(0.,6)
b = np.array([1.,2,3,4,5])
np.all(a)


False

In [147]:
a = np.arange(25).reshape(5,5)
a[1][2] = 0
print(a.shape)
a.all(axis=0)
#0이 있으면 False 아니면 True axis=0은 세로줄 0여부 axis=1은 가로줄 0 여부

[[ 0  1  2  3  4]
 [ 5  6  0  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([False, False,  True,  True,  True])

In [152]:
#슬라이싱(자르기)
a[0,:]

array([0, 2, 4])

In [154]:
a[:,0]

array([ 0,  5, 10, 15, 20])

In [155]:
a[:3,:3].reshape(-1)

array([ 0,  1,  2,  5,  6,  0, 10, 11, 12])

In [158]:
#2차원구조
a[[0],:]

array([[0, 1, 2, 3, 4]])

In [165]:
#2x7의 array에서 row를0,1갖고 3,6을 슬라이스
np.arange(2*7).reshape(2,7)[:,3:]

array([[ 3,  4,  5,  6],
       [10, 11, 12, 13]])

In [178]:
a= np.arange(2*7).reshape(2,7)
a[:,3:] = [[1,2,3,4],
           [5,6,7,8]]
a

array([[0, 1, 2, 1, 2, 3, 4],
       [7, 8, 9, 5, 6, 7, 8]])

In [180]:
b = (1,2,3,4,5)
for i in b:
  print(b)

(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)


In [189]:
b = np.arange(1,9).reshape(2,2,2)
print(b)
b[:,[1],:].shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 1, 2)

In [191]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [194]:
t = np.full((3,3),4)

In [198]:
np.repeat(t,3,axis=0)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [199]:
t = np.array([[1,2,3],
              [4,5,6]
              ])

In [201]:
np.repeat(t,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [206]:
t = np.ones((5,5))
t[1:4,1:4]=np.zeros((3,3))
t[2,2]=9
t.astype(np.int64)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [207]:
l = [1,2,3,4]
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
a + 2

In [ ]:
a * 2

In [ ]:
a - 2

In [ ]:
a / 2

In [ ]:
a * a

In [221]:
a + l

array([2, 4, 6, 8])

In [222]:
a + [[1],
     [2]
     ]

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [223]:
a.mean()

2.5

In [226]:
#평균 오류X
np.mean(a)

2.5

In [227]:
np.median(a)

2.5

In [228]:
#표준편차
np.std(a)

1.118033988749895

In [229]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [230]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [231]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [ ]:
np.cos( np.deg2rad(180) )

In [ ]:
data = np.random.randn(10,20)*100
data

In [268]:
np.savetxt("random.csv".data.delimiter=",")

SyntaxError: ignored

In [ ]:
data>40

In [ ]:
data[data>40]

In [259]:
np.mean(data[data>40])

109.09964228386835

In [263]:
np.sum(data[:,:])

1197.6943441892745